# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_data_Dialog(object):
    def setupUi(self, check_data_Dialog):
        check_data_Dialog.setObjectName("check_data_Dialog")
        check_data_Dialog.resize(340, 190)
        check_data_Dialog.setMinimumSize(QtCore.QSize(340, 190))
        check_data_Dialog.setMaximumSize(QtCore.QSize(340, 190))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        check_data_Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(check_data_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(check_data_Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(0, 28))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(check_data_Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(150, 28))
        self.label_2.setMaximumSize(QtCore.QSize(150, 28))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.rh_max_textEdit = QtWidgets.QTextEdit(check_data_Dialog)
        self.rh_max_textEdit.setMinimumSize(QtCore.QSize(80, 28))
        self.rh_max_textEdit.setMaximumSize(QtCore.QSize(80, 28))
        self.rh_max_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rh_max_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rh_max_textEdit.setObjectName("rh_max_textEdit")
        self.gridLayout.addWidget(self.rh_max_textEdit, 3, 2, 1, 1)
        self.temp_min_textEdit = QtWidgets.QTextEdit(check_data_Dialog)
        self.temp_min_textEdit.setMinimumSize(QtCore.QSize(80, 28))
        self.temp_min_textEdit.setMaximumSize(QtCore.QSize(80, 28))
        self.temp_min_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_min_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_min_textEdit.setObjectName("temp_min_textEdit")
        self.gridLayout.addWidget(self.temp_min_textEdit, 2, 0, 1, 1)
        self.temp_max_textEdit = QtWidgets.QTextEdit(check_data_Dialog)
        self.temp_max_textEdit.setMinimumSize(QtCore.QSize(80, 28))
        self.temp_max_textEdit.setMaximumSize(QtCore.QSize(80, 28))
        self.temp_max_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_max_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.temp_max_textEdit.setObjectName("temp_max_textEdit")
        self.gridLayout.addWidget(self.temp_max_textEdit, 2, 2, 1, 1)
        self.rh_min_textEdit = QtWidgets.QTextEdit(check_data_Dialog)
        self.rh_min_textEdit.setMinimumSize(QtCore.QSize(80, 28))
        self.rh_min_textEdit.setMaximumSize(QtCore.QSize(80, 28))
        self.rh_min_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rh_min_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rh_min_textEdit.setObjectName("rh_min_textEdit")
        self.gridLayout.addWidget(self.rh_min_textEdit, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(check_data_Dialog)
        self.label.setMinimumSize(QtCore.QSize(150, 28))
        self.label.setMaximumSize(QtCore.QSize(150, 28))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(check_data_Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)

        self.retranslateUi(check_data_Dialog)
        QtCore.QMetaObject.connectSlotsByName(check_data_Dialog)

    def retranslateUi(self, check_data_Dialog):
        _translate = QtCore.QCoreApplication.translate
        check_data_Dialog.setWindowTitle(_translate("check_data_Dialog", "Ограничения данных"))
        self.label_3.setText(_translate("check_data_Dialog", "Проверка входных данных"))
        self.label_2.setText(_translate("check_data_Dialog", "RH, %"))
        self.rh_max_textEdit.setHtml(_translate("check_data_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">max</p></body></html>"))
        self.temp_min_textEdit.setHtml(_translate("check_data_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">min</p></body></html>"))
        self.temp_max_textEdit.setHtml(_translate("check_data_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">max</p></body></html>"))
        self.rh_min_textEdit.setHtml(_translate("check_data_Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">min</p></body></html>"))
        self.label.setText(_translate("check_data_Dialog", "Temperature, °C"))
        self.pushButton.setText(_translate("check_data_Dialog", "Принять"))
